---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/fedora/fedora:39
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 1
      stdout_callback: yaml
      bin_ansible_callbacks: true
verifier:
  name: ansible
