---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Get stats of directory created by role
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.config/secrets"
